{\rtf1\ansi\ansicpg1252\cocoartf1348\cocoasubrtf170
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720

\f0\fs24 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 # Sample .travis.yml for R projects\
\
language: r\
warnings_are_errors: false\
\
notifications:\
  email:\
    on_success: change\
    on_failure: change\
\
r_apt_packages:\
  - testthat\
  - knitr\
  - reshape2\
  - ggplot2\
  - plyr\
  - mvtnorm\
  - boot\
  - msm\
  - statmod\
  - gridExtra\
\
r_github_packages:\
  - jimhester/covr\
  - atredennick/IPMdoit\
\
after_success:\
  - Rscript -e 'library(covr); coveralls()'\
\
sudo: required\
}